name: build-and-push-ghcr

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout canvas-lms sibling
        uses: actions/checkout@v4
        with:
          repository: instructure/canvas-lms
          ref: d5a99e9294e374e83f41197adce94aedf394750f
          path: canvas-lms
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (amd64 only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./canvas-self-hosted/Dockerfile.production
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/canvas-self-hosted:${{ github.sha }}
          build-args: |
            NODE_MAJOR=18
            YARN_VERSION=1.19.1-1
            RUBY_MAJOR=3.1
