name: Build & Push Canvas Docker image

on:
  workflow_dispatch:   # run from the GitHub UI
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write   # needed to push to GHCR
  id-token: write   # not required for this flow, but common to include

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your repo has submodules you can enable them:
          submodules: 'recursive'

      - name: Checkout canvas-lms at specific commit into canvas-lms/
        # checkout the external repository into path "canvas-lms"
        uses: actions/checkout@v4
        with:
          repository: instructure/canvas-lms
          ref: d5a99e9294e374e83f41197adce94aedf394750f  # the commit you specified
          path: canvas-lms
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (multi-platform)
        # adjust platforms and tags as you want
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/canvas-self-hosted:${{ github.sha }}
          # If you prefer a 'latest' tag too, add -t ghcr.io/${{ github.repository_owner }}/canvas-self-hosted:latest
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --file canvas-lms/Dockerfile.production \
            --tag "${IMAGE}" \
            canvas-lms
          echo "Pushed ${IMAGE}"
